/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import indexa.busca.Construtor;
import indexa.busca.Documento;
import indexa.busca.Par;
import EstruturasHashTable.TabelaHash;
import EstruturasTrie.Trie;
import indexa.busca.DocumentoRelevante;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Qih
 */
public class FrameInicio extends javax.swing.JFrame {
    TabelaHash tabela;
    Trie trie;
    /**
     * Creates new form FrameInicio
     */
    public FrameInicio() {
        initComponents();
        btnBuscaMulti.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnCarregar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        qtdDocumentosField = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        tamanhoTabelaField = new javax.swing.JFormattedTextField();
        jComboBox1 = new javax.swing.JComboBox();
        checkIgnorar = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        chaveBuscaField = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnBuscaMulti = new javax.swing.JButton();
        btnBuscaPT = new javax.swing.JButton();
        btnBuscaEN = new javax.swing.JButton();
        btn100p = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCarregar.setText("Carregar Arquivo");
        btnCarregar.setActionCommand("");
        btnCarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarActionPerformed(evt);
            }
        });

        jLabel3.setText("Criação da Estrutura");

        jLabel5.setText("Quantidade de documentos a serem lidos:");

        qtdDocumentosField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));
        qtdDocumentosField.setText("0");
        qtdDocumentosField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtdDocumentosFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("Tamanho da tabela:");

        tamanhoTabelaField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));
        tamanhoTabelaField.setText("0");
        if(jComboBox1.getSelectedIndex()==0){
            tamanhoTabelaField.setEnabled(false);
        }
        tamanhoTabelaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tamanhoTabelaFieldActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tabela Hash", "Trie" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        checkIgnorar.setLabel("Ignorar palavras mais frequentes");
        checkIgnorar.setOpaque(false);
        checkIgnorar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkIgnorarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tamanhoTabelaField, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(qtdDocumentosField, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCarregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(checkIgnorar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtdDocumentosField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(checkIgnorar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCarregar)
                    .addComponent(tamanhoTabelaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel4.setText("Busca");

        jLabel1.setText("Digite o termo de busca:");

        chaveBuscaField.setEditable(false);
        chaveBuscaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chaveBuscaFieldActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.setEnabled(false);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnBuscaMulti.setText("buscaMultiplas");
        btnBuscaMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaMultiActionPerformed(evt);
            }
        });

        btnBuscaPT.setText("BuscaPT");
        btnBuscaPT.setEnabled(false);
        btnBuscaPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaPTActionPerformed(evt);
            }
        });

        btnBuscaEN.setText("BuscaEN");
        btnBuscaEN.setEnabled(false);
        btnBuscaEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaENActionPerformed(evt);
            }
        });

        btn100p.setText("100Palavras");
        btn100p.setEnabled(false);
        btn100p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn100pActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chaveBuscaField, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar)))
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btnBuscaMulti)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn100p)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscaPT))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnBuscaEN)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(chaveBuscaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscaMulti)
                    .addComponent(btnBuscaPT)
                    .addComponent(btn100p))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscaEN)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jLabel2.setText("Documentos");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2)
        );

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Importância", "Documento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable);
        if (jTable.getColumnModel().getColumnCount() > 0) {
            jTable.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chaveBuscaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chaveBuscaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chaveBuscaFieldActionPerformed

    private void btnCarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarActionPerformed
      
        int returnVal = fc.showOpenDialog(FrameInicio.this);
            ArrayList<String> palavrasIgnorar = new ArrayList<String>();
            
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                //Pega o arquivo
                File file = fc.getSelectedFile();
                Construtor c = new Construtor();
                int qtdDocumentos,tamanhoTabela;                                
                //Trata erro de input incorreto
                try{
                    qtdDocumentos = Integer.parseInt(qtdDocumentosField.getText());
                    tamanhoTabela = Integer.parseInt(tamanhoTabelaField.getText());
                }catch(NumberFormatException e){
                    qtdDocumentos =0;
                    tamanhoTabela =0;
                    showMessageDialog(null, "Número inválido, a tabela será construída com valores padrão.");
                }
                //Só numeros positivos, por favor
                qtdDocumentos = Math.abs(qtdDocumentos);
                tamanhoTabela = Math.abs(tamanhoTabela);
                if(qtdDocumentos != 0){
                    qtdDocumentos++;
                }
                if(jComboBox1.getSelectedItem().toString() == "Tabela Hash"){                    
                    if(checkIgnorar.isSelected()==false){                        
                        palavrasIgnorar.add(" ");      
                    }else{
                        Object[] o = c.contaEignora(file);
                        palavrasIgnorar = (ArrayList<String>) o[1];
                    }
                    
                   this.tabela = c.criaTabela(file,qtdDocumentos,tamanhoTabela,palavrasIgnorar);
                   
                }
                else{
                    if(checkIgnorar.isSelected()==false){                        
                        palavrasIgnorar.add(" ");      
                    }else{
                        Object[] o = c.contaEignora(file);
                        palavrasIgnorar = (ArrayList<String>) o[1];
                    }
                   this.trie = c.criaTrie(file, qtdDocumentos, palavrasIgnorar);
                }
                btnBuscar.setEnabled(true);
                btnCarregar.setEnabled(false);
                btnCarregar.setText("Arquivo Carregado");
                chaveBuscaField.setEditable(true);
                qtdDocumentosField.setEditable(false);
                tamanhoTabelaField.setEditable(false);
                checkIgnorar.setEnabled(false);
                jComboBox1.setEnabled(false);
                btnBuscaEN.setEnabled(true);
                btnBuscaPT.setEnabled(true);
                if(jComboBox1.getSelectedItem().toString() == "Tabela Hash"){
                    btn100p.setEnabled(true);
                }
                
                c.memoria();
    
            } else {
            
            }
            
    }//GEN-LAST:event_btnCarregarActionPerformed

    private void qtdDocumentosFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtdDocumentosFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtdDocumentosFieldActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        long startTime = System.nanoTime();
        String chave = chaveBuscaField.getText();
        Documento d = new Documento();
        chave = d.trataLinha(chave);
        String[] chavesMultiplas = d.identificaPalavras(chave);
        //temos somente uma chave de busca
        if(chavesMultiplas.length==1){
            //Busca na tabela hash
            if(jComboBox1.getSelectedItem().toString() == "Tabela Hash"){  
                ArrayList<Par> listPares = tabela.busca(chave);
                if(listPares==null){
                    showMessageDialog(null, "Nenhum documento encontrado, desculpe...");
                    return;
                }
                Par pAux;
                int docId;
                String docUrl;

                DefaultTableModel model = (DefaultTableModel) jTable.getModel();
                model.setRowCount(0);
                int j=1;
                for (int i = 0; i < listPares.size(); i++) {
                    pAux = listPares.get(i);
                    docId = pAux.getDoc_id();
                    docUrl =  "http://dbpedia.org/resource/"+tabela.getIndex(docId).getUrl();

                    Object[] ob = {(j),docUrl};
                    model.addRow(ob);
                    j++;
                }
            }
            //ENTAO VAMOS BUSCAR NA TRIE
            else{

                ArrayList<Par> listPares = trie.busca(chave);
                if(listPares==null){
                    showMessageDialog(null, "Nenhum documento encontrado, desculpe...");
                    return;
                }
                Par pAux;
                int docId;
                String docUrl;

                DefaultTableModel model = (DefaultTableModel) jTable.getModel();
                model.setRowCount(0);
                int j=1;
                for (int i = 1; i < listPares.size(); i++) {
                    pAux = listPares.get(i);
                    docId = pAux.getDoc_id();
                    docUrl =  "http://dbpedia.org/resource/"+trie.getIndex(docId).getUrl();

                    Object[] ob = {(j),docUrl};
                    model.addRow(ob);
                    j++;
                }
            }
        }else{//Temos 2 ou mais chaves de busca
            chave = chaveBuscaField.getText();
            d = new Documento();
            chavesMultiplas = d.identificaPalavras(chave);
            //Busca na tabela hash
            if(jComboBox1.getSelectedItem().toString() == "Tabela Hash"){  
                ArrayList<Par> listPares = tabela.buscaMultiplas(chavesMultiplas);
                if(listPares==null || listPares.size()==0){
                    showMessageDialog(null, "Nenhum documento encontrado, desculpe...");
                    return;
                }
                Par pAux;
                int docId;
                String docUrl;

                DefaultTableModel model = (DefaultTableModel) jTable.getModel();
                model.setRowCount(0);
                int j=1;
                //for (int i = 0; i < listPares.size(); i++) {
                for (int i = listPares.size()-1; i >= 0; i--) {
                    pAux = listPares.get(i);
                    docId = pAux.getDoc_id();
                    docUrl =  "http://dbpedia.org/resource/"+tabela.getIndex(docId).getUrl();

                    Object[] ob = {(j),docUrl};
                    model.addRow(ob);
                    j++;
                }
            }else{
                ArrayList<Par> listPares = trie.buscaMultiplas(chavesMultiplas);
                if(listPares==null || listPares.size()==0){
                    showMessageDialog(null, "Nenhum documento encontrado, desculpe...");
                    return;
                }
                Par pAux;
                int docId;
                String docUrl;

                DefaultTableModel model = (DefaultTableModel) jTable.getModel();
                model.setRowCount(0);
                int j=1;
                //for (int i = 0; i < listPares.size(); i++) {
                for (int i = listPares.size()-1; i >= 0; i--) {
                    pAux = listPares.get(i);
                    docId = pAux.getDoc_id();
                    docUrl =  "http://dbpedia.org/resource/"+trie.getIndex(docId).getUrl();

                    Object[] ob = {(j),docUrl};
                    model.addRow(ob);
                    j++;
                }
            }
        }
        
        long endTime = System.nanoTime();
        long duration = (endTime - startTime); 
        double seconds = (double)duration / 1000000000.0;
        System.out.println("Tempo gasto para consulta: "+seconds+"segundos");
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String selecionado = (String)jComboBox1.getSelectedItem();
        if(selecionado == "Trie"){
            jLabel6.setVisible(false);
            tamanhoTabelaField.setVisible(false);
        }else{
            jLabel6.setVisible(true);
            tamanhoTabelaField.setVisible(true);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void tamanhoTabelaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tamanhoTabelaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tamanhoTabelaFieldActionPerformed

    private void checkIgnorarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkIgnorarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkIgnorarActionPerformed

    private void btnBuscaMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaMultiActionPerformed
        // TODO add your handling code here:
        String chave = chaveBuscaField.getText();
        Documento d = new Documento();
        String[] chavesMultiplas = d.identificaPalavras(chave);
        //Busca na tabela hash
        if(jComboBox1.getSelectedItem().toString() == "Tabela Hash"){  
            ArrayList<Par> listPares = tabela.buscaMultiplas(chavesMultiplas);
            if(listPares==null){
                showMessageDialog(null, "Nenhum documento encontrado, desculpe...");
                return;
            }
            Par pAux;
            int docId;
            String docUrl;

            DefaultTableModel model = (DefaultTableModel) jTable.getModel();
            model.setRowCount(0);
            int j=1;
            for (int i = 0; i < listPares.size(); i++) {
                pAux = listPares.get(i);
                docId = pAux.getDoc_id();
                docUrl =  "http://dbpedia.org/resource/"+tabela.getIndex(docId).getUrl();

                Object[] ob = {(j),docUrl};
                model.addRow(ob);
                j++;
            }
        }else{
            ArrayList<Par> listPares = trie.buscaMultiplas(chavesMultiplas);
            if(listPares==null){
                showMessageDialog(null, "Nenhum documento encontrado, desculpe...");
                return;
            }
            Par pAux;
            int docId;
            String docUrl;

            DefaultTableModel model = (DefaultTableModel) jTable.getModel();
            model.setRowCount(0);
            int j=1;
            for (int i = 0; i < listPares.size(); i++) {
                pAux = listPares.get(i);
                docId = pAux.getDoc_id();
                docUrl =  "http://dbpedia.org/resource/"+trie.getIndex(docId).getUrl();

                Object[] ob = {(j),docUrl};
                model.addRow(ob);
                j++;
            }
        }
    }//GEN-LAST:event_btnBuscaMultiActionPerformed

    private void btnBuscaPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaPTActionPerformed
        // TODO add your handling code here:
        tabela.fazBuscas(tabela.PTumaChave, tabela.PTduasChaves, tabela.PTtresChaves);
    }//GEN-LAST:event_btnBuscaPTActionPerformed

    private void btn100pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn100pActionPerformed
        // TODO add your handling code here:
        tabela.palavrasAleatorias();
    }//GEN-LAST:event_btn100pActionPerformed

    private void btnBuscaENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaENActionPerformed
        // TODO add your handling code here:
        tabela.fazBuscas(tabela.ENumaChaves, tabela.ENduasChaves, tabela.ENtresChaves);
    }//GEN-LAST:event_btnBuscaENActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameInicio().setVisible(true);
            }
        });
    }

    JFileChooser fc = new JFileChooser();
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn100p;
    private javax.swing.JButton btnBuscaEN;
    private javax.swing.JButton btnBuscaMulti;
    private javax.swing.JButton btnBuscaPT;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCarregar;
    private javax.swing.JTextField chaveBuscaField;
    private javax.swing.JCheckBox checkIgnorar;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JFormattedTextField qtdDocumentosField;
    private javax.swing.JFormattedTextField tamanhoTabelaField;
    // End of variables declaration//GEN-END:variables
}
